# Generated by Django 4.2 on 2023-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_meanings_sentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makesentence',
            name='meaning',
            field=models.TextField(default='', max_length=255),
        ),
    ]
